Contacts/People/authors.mixer
Contacts/People/modules.mixer
lib/addresses

This adds @ChrisJefferson and @markuspf to the author lists, and also adds them to the list of kernel maintainers; it also removes Werner Nickel from the list of maintainers.
In general, the lists of persons contains many outdated addresses; and I am also somewhat doubtful about some of the module maintainers still listed... But with this it is at least a little bit better.

Update author and maintainers list a bit

---

Download/tools.mixer

Also remove a reference to GMP, as we soon will *always* require GMP.

Mention C++ compiler is recommended

---

Contacts/People/modules.mixer

Update website with me being not only maintainer but also author of the module. (I hope I put it into the appropriate file, I was thinking about the bottom of the site http://gap-system.org/Contacts/People/modules.html )

Add Gabor Horvath as StructureDescription module author

---

Download/tools.mixer

This updates the page http://www.gap-system.org/Download/tools.html with some Ubuntu/Debian based dependencies that might help newcomers with building packages properly. 
I believe that this page should be kept uptodate and I feel that it should mainly be the package authors responsibility to help keeping this website always current and updated. We should not expect a newcomer to GAP or to linux knowing what _development_ packages they need to install for e.g. xgap when the manual only says "X window system in the Version 11 Release 5 or newer".... (Anyway, after some thinking and trial-and-error, I figured it out from the output of ````BuildPackages.sh```` and this website).
I have not checked ParGAP, yet, and as of now, I have failed to build float, fr, linboxing, …

Update tools with distribution package depends

---

Download/alternatives.mixer

This morning I've got an email from a user telling he can't download GAP 4.8.7 from an FTP server. It happens that FTP was in his old script, not on the GAP website. Anyhow, this triggered issue #32 and revising the alternatives page (https://www.gap-system.org/Download/alternatives.html) in this PR.

Revised list of alternative ways to use GAP

---

Contacts/Forum/forum.mixer
Doc/forumarchive.mixer
Download/alternatives.mixer
Download/index.mixer
Faq/faq.mixer
Releases/4.7.6.mixer
Releases/4.7.7.mixer
gap.mixer
search.mixer

This fixes links to the mailing list archives, which do not work anymore via http.

Change more links from http:// to https://

---

Download/index.mixer
Download/install.mixer
Download/upgrade.mixer

This PR revises [Installation](https://www.gap-system.org/Download/index.html) section of the GAP website and resolves #79. It's incremental, and does not do things much better because of time limitations, but at least it removes some outdated statements and clarifies some instructions, so it will be helpful to merge it now before announcing GAP 4.9.1 release.

Revise pages under "Installation" section

---

Packages/undep.mixer

The Gap.app description was out-of-date, and the links provided were old.  Updated to indicate that it works with recent GAP versions and macOS versions, and that it's more than an XGAP clone.
I tried to keep a neutral tone, but am not offended by edits if I failed.

update Gap.app description and links

---

lib/gwstart.tmpl

@ChrisJefferson noticed a seemingly "broken" FAQ page. This was caused by an outdated link which points to an ancient version of the FAQ. This PR updates that link. But in addition, it would be good to remove the outdated FAQ from the server.

Update a link to an ancient FAQ copy

---

_layouts/default.hml

Fixes a mistake in default.html (title instead of page.title), which makes the title of the page also appear at the top of the text.

Fix displaying title at top of content

---

Contacts/centres.html
Contacts/cite.html
Contacts/contacts.html
Contacts/funding.html
Contacts/index.html
Contacts/index.mixer
Contacts/outside.html
Contacts/publicationfeedback.html
Contacts/submit.html
Contacts/trouble.html

This converts the files in the 'Contacts' directory, but not it's subdirectories.
The only interesting thing was converting the `<mixer person=GAP` parts.

Convert base directory of 'Contacts'

---

Download/index.html

Now if things go wrong your are linked to the installation instructions of the master branch of GAP

Changed a link in Download/index.html

---

Datalib/prim.html
Datalib/tom.html
Datalib/trans.html

The symlinks resulted in very strange things. Like, take a look at https://www.gap-system.org/Datalib/trans.html it is identical to https://www.gap-system.org/Packages/transgrp.html which is weird.
The alternative would be to turn these pages into redirects, but that also seems iffy... Then again, these pages don't turn up in the navigation (and that's good, IMHO!) but there *are* links to it inside our site: from the Faq and from Gap3...

Datalib: replace symlinks with redirections

---

Download/upgrade.html

It's an outmoded model of working; I'd rather improve PackageManager and suggest *that* to people.
This is part of content cleanup, I guess

Jekyll: don't mention SuggestUpgrades

---

Doc/Bib/convbib.g
_data/bib_stats_msc.yml

I have figured out the reason of those seemingly random changes I observed a couple of days in a row while working on `Doc/Bib` content. This will avoid them by fixing the screen width. 
This regenerates one of the data file (should be done as a part of my previous PR).

Fix screen width when outputting some GAP bibliography pages

---

Doc/Learning/learning.html
Doc/Teaching/teaching.html

Update GAP use in Teaching page:
- reorder to put most recent first
- add some materials collected at https://github.com/gap-system/GapWWW/issues/148
- add some more sources reported elsewhere

Updates of GAP use in teaching page

---

Contacts/People/Council/council.html
Contacts/cite.html
Doc/manuals.html
Download/copyright.html
Download/index.html
Download/install.html
Download/upgrade.html
_data/gap.yml
_data/release.yml
index.html

I have broken out the GAP release version number, date, and year from `_data/gap.yml` into this separate file. This should make it very easy for a script to update this file as part of an automated release process.
I have also put the `gap411dist` etc variables in `_data/gap.yml` into the end of the file; these are the only remaining values in this file which will we should expect to be added to, so a script could easily append to this file to add a `gap412dist` variable, say.

Create _data/release.yml file

---

_layouts/packages.html

Since we are stopping creating and hosting individual package archives, it might be a good idea to link to the archives listed in the package's `PackageInfo.g`.
Resolves #230.

Show links to upstream archives on package pages

---

_Packages/deepthought.html
_Packages/semigroups.html

Although this isn't an ideal or permanent solution, I've had several reports about the broken links to the Semigroups website, so I'd like to get it fixed for now.
See #234 for thoughts on how to handle this situation better.

Manually update URLs for the Semigroups and DeepThought packages

---

_Releases/4.11.1.html

I have mostly copied the text from the Windows bit of the previous release, i.e. https://www.gap-system.org/Releases/4.11.0.html. In addition, I have made the recommended Windows route to be with the Windows Subsystem for Linux - I hope this is uncontroversial.
But I do not know whether the details that it contains are still accurate (about GMP, readline, spaces in filenames, etc). @alex-konovalov please can you check that the details are accurate?

Link to 64-bit .exe for GAP 4.11.1

---

Doc/Bib/GapCite.notyet

Adds [a paper](https://arxiv.org/abs/2105.09117) citing GAP to the references of not yet published papers citing GAP.

Adds a paper on the arxiv citing GAP.

---

.github/workflows/sync.yml

This workflow won't run here. Eventually, it will be manually triggered by a button in the `Actions` tag of this repository, and it will run automatically every night.
A demonstration of the result can be seen on my fork https://github.com/wilfwilson/GapWWW, in particular, in PR https://github.com/wilfwilson/GapWWW/pull/9, which updates the website for a fake GAP v4.12.0 that I made on my fork.

GitHub Actions Workflow for sync the GAP GitHub releases data to the website

---

.github/workflows/build.yml
.travis.yml

This is currently quite slow (3½ minutes), but since we don't run it very often I don't think we should spend time speeding it up just yet.
This doesn't actually do anything with the built site, but it at least lets us see if a pull request or push is going to actually break the website such that it doesn't build.
This runs on pushes, on PRs, and can be manually dispatched.
This resolves the original issue raised in #236, but not the bigger suggestion of @fingolfin; I'll either make a new issue for that, or rename #236.

Replace Travis with GitHub Actions for testing whether the site builds

---

Doc/manuals.html

The links to manuals would use the `InstallationPath` value of a package for its directory name, but this sometimes includes the version number. However, the `extract_manuals.py` script now strips any version number from the directory name when extracting the package manuals for uploading to the website.
So we now need to remove any version numbers when making the links too. I do this by stripped anything after (and include) a hyphen, but this is risky if a package ever properly contains a hyphen as part of its name. Would it be safe to just use `dir = pkg[1].PackageName`?
Fixes #252.
Thanks to @veni-vidi-code for the report.

Fix broken links to package manuals

---

Download/index.html
Download/install.html

This does not deal with the bigger questions such as:
- why do we provide these instructions in two places?
- should we provide them in this form at all, or shouldn't we just link to `INSTALL.md` (resp. integrate `INSTALL.md` more tightly into the website

Mention required tools in install instructions

---

Contacts/submit.html

The linked page does not exist. But I have corrected the link to point to the page that does have the appropriate information.

Fix a link on `Contacts/submit.html`

---

Packages/Authors/authors.html

I have tried to fix wrong statements.
~Afterwards, one thing is still wrong on the page:~
> ~This format is partly documented in the document "The gapmacro.tex Manual Format" which is included in the ``tools'' archive contained in the etc directory of the GAP installation.~
~I find files concerning `gapmacro.tex` in the `doc` directory. Is this the official location for them?~

fixed a few inconsistencies

---

_layouts/core.html
_layouts/start.html

We just link to the imprint and privacy policy of TU Kaiserslautern for
now. Since those refer explicit to a "Contact" link, also make
one clearly visible next to the other two new links in the navbar.
In exchange, remove the footer email link "The GAP Group", it seems
redundant.
Here is a preview of how the changed navbar looks like. It's not great (clearly we need a full redesign), but IMHO "good enough".
Resolves #273

Add an imprint and privacy policy to comply with GPDR

---

Datalib/perfect.html

To be merged once 4.12.0 is out.

GAP 4.12.0 contains perfect groups up to 2*10^6

---

_layouts/releases.html

There is no need to worry about spaces in GAP 4.12.
I haven't been able to build this to test it (sorry!) as my computer is being stupid.

Remove mentions of directories with spaces for GAP 4.12

---

Download/alternatives.html

Since GAP 4.11 the rsync distribution of GAP was restarted (with a different technology because before we could not update from 4.7.6 for technical reasons). Is is now upgraded to GAP 4.12.0.

Change description of rsync distribution

---

_layouts/releases.html

Update deprecated term "OS X" to "macOS"

---

Download/tools.md

- Convert Download/tools.html to Markdown
- Improve instructions for installing Apple Xcode
However, this is not the last word: this page has quite some overlap with `INSTALL.md` shipped with GAP. Arguably the latter has far more information, though some things on the Tools page are not yet in there... Perhaps we should migrate all contents of the tools page into `INSTALL.md`, then replace the former with a link to the latter? The idea here being that we hardly manage to keep this information up-to-date in one place; having it in multiple places just makes things even worse.

Improve tools page

---

Packages/undep.html

- remove references to GGAP and 4.4.12 installers
- remove a gratuitous reference to Sage (of course it is fine for us to
point out to people that one can use Sage to access Sage, but not
*there*)
- remove references to various packages that are now deposited (LieRing,
QPA) or were superseded by a deposited GAP package (pg -> fining)
- update a bunch of links

Update "Undeposited Implementations for GAP" page

---

Packages/packages.html

We don't want to replace this with another link, the existing link to the (archive) repository is enough.
Resolves #214. Closes #215

Remove broken happrime link

---

Contacts/People/supportgroup.md

Resolves #202.
However, we should check back who really wants to be on the list (resp. whom *we* want on the list, and how to decide it?)

Update supportgroup to match actual list members

---

Download/alternatives.html

Can be re-enabled if/when these are up-to-date again

Disable reference to outdated docker containers

---

Contacts/contacts.md

Moderators of the support mailing list are seeing a LOT of emails coming
from people who really want to contact the support of the GAP clothing
company. They are finding our email address via a Google search for 'how
do I email gap', which prompts Google to show a 'snippet' text from our
website -- namely the text modified by this patch. With the revision, I
hope that either Google will stop showing this snippet, or that at least
some people will realize that this is the wrong GAP.

Tweak a pointer to the support email address

---

_data/package-infos/4-11-0.json
_data/package-infos/4-11-1.json
_data/package-infos/4-12-0.json
_data/package-infos/4-12-1.json
_data/package-infos/4-12-2.json
_data/package_status.yml
_includes/packagelink_list_accepted.html
_includes/packagelink_list_deposited.html
_layouts/packages.html

Instead of letting each package keep track of its own status as a
deposited or refereed package, we now collect this information
centrally. This makes more sense, and also avoids some awkwardness
For example, in order to be accepted for distribution, currently GAP
package authors must provide a proper release of their package, which
then is reviewed. But that release should not yet have status `accepted`
resp. `deposited`... so strictly speaking, right after the package is
officially accepted, a second release with the updated status should be
made right away.
With a centralized list of deposited and accepted packages, there is no
need anymore for packages metadata to contain this information.

Centralize package status into a single file

---

copyright.md
install/windows.md

One tiny typo, and also some minor adjustment of how we talk about windows.
In particular, putting in directories with spaces is fine, and by default we install into 'Program Files' nowadays, like any windows program.

Tiny fixes

---

packages/index.md

... so that even users without JavaScript see at least *something*.

Pre-populate packages table

---

_includes/title.html
_sass/color_schemes/darkgap.scss
_sass/color_schemes/lightgap.scss
_sass/custom/custom.scss
_sass/custom/setup.scss

At the moment, dark mode has a rather dark blue against the dark grey, which doesn't look great.  This PR would use our "GAP light" colour, assuming I haven't made any mistakes.
(I'm having trouble testing locally)

Change title colour for dark mode

---

about/capabilities/algebras.md
about/capabilities/basic.md
about/capabilities/fpgroups.md
about/capabilities/further.md
about/capabilities/groups.md
about/capabilities/index.md
about/capabilities/permgroups.md
about/capabilities/representations.md
about/capabilities/semigroups.md
about/capabilities/words.md
faq.md
install/index.md
packages/authors/index.md
packages/authors/variablenames.md

If you go to https://www.gap-system.org/capabilities/groups , and look at the first sentence, you will notice there is no whitespace before every link. This seems to be a consistent problem, across much of the site.
The issue is the use of `{%-` , which eats whitespace, instead of `{%`, which leaves it in.
I've tried to make a pass over all links, and look for this issue. I haven't edited some cases (notably inside _includes/ref.html, and some code in index.md), as there there are a series of tags, and the whitespace removal is on purpose.
I will admit I didn't go and check every single line I editted, but I do a bunch of random spot checks, and they either looked the same (as they were at the start of a line), or were improved, and I thought changing all cases in 'natural text' was best, …

Clean up whitespace around references

---

index.md

I think "installation" sounds better, and also the title of the installation page is "installation", so I think it's the more accurate one too.

On `index.md`: change "install page" to "installation page"

---

.github/workflows/sync.yml

It seems the `dev/release` folder has been changed at some point to `dev/releases`.

Fix a file path in the default PR message when syncing website data
