- lib/addresses
I am not sure whether the editor used utf8 or latin... I certainly wanted to use the accented character á...
I just have no idea how to build the webpage to check....
> Add Gabor Horvath's address data

- Contacts/People/authors.mixer
Added Gabor Horvath to authors list.
> Added Gabor Horvath to authors list.

- Contacts/People/modules.mixer
This is a test pull request.
I've edited the file in the browser. Indeed, I've edited only one line, but it changes encoding and shows changes in all lines with umlauts.
> GAP library of functions -> GAP library

- Packages/Contrib/emacs.mixer
if anyone has a copy, perhaps it can be resurrected...
> remove a dead link

- lib/gw.css
- lib/gw.tmpl
- lib/gwdatalib.tmpl
- lib/gwgap3.tmpl
- lib/gwstart.tmpl
... which links to the start page of the GAP homepage. That's a
common pattern for websites.
> Turn top left "GAP" white-on-blue cell into link

- Download/Updates/index.mixer
- Packages/Authors/authors.mixer
> Update links to Changes manual and mention PackageMaker

- Download/Updates/gap4r4p10.mixer
- Download/Updates/gap4r4p11.mixer
- Download/Updates/gap4r4p5.mixer
- Download/Updates/gap4r4p6.mixer
- Download/Updates/gap4r4p8.mixer
> Fix cross-references to manual section in old Updates pages

- Packages/packages.mixer
- Packages/packages_list.g
Also added the script to generate lists based on their status. Closes #50.
> Fixed the list of packages on the package overview page.

- Doc/Teaching/teaching.mixer
Una introducción al álgebra con GAP by @vendramin located at http://mate.dm.uba.ar/~lvendram/lectures/GAP.pdf
> Add link to teaching material in Spanish by Leandro Vendramin.

- Contacts/People/supportgroup.mixer
> Add link to issue tracker to Support Group page

- Doc/Bib/GapNonMR.bib
Add @wilfwilson's PhD thesis, and fix a typo in @mtorpey's.
> Bibliography: add W. A. Wilson's PhD thesis

- lib/addresses
Also change three instances of "Professor" to "Prof.", to match
the rest of the entries in this file.
> addresses: AH and me professors

- Contacts/centres.mixer
- Doc/Examples/p-group.mixer
- Doc/History/history.mixer
- Faq/faq.mixer
- Packages/Authors/authors.mixer
- Packages/packages.mixer
Most of them were changed to GAP in PR #125
> Clean up remaining <mixer var="GAP"/>

- Contacts/Forum/forum.html
- Contacts/Forum/index.html
- Contacts/Forum/index.mixer
Convert another small directory.
> Convert Contacts/Forum

- Contacts/People/Council/council.html
- Contacts/People/Council/index.html
- Contacts/People/Council/index.mixer
- Contacts/People/authors.html
- Contacts/People/index.html
- Contacts/People/index.mixer
- Contacts/People/modules.html
- Contacts/People/people.html
- Contacts/People/supportgroup.html
This finishes off translating the 'People' folder.
This does dump all information about people except their name, but I feel that is (a) not out of date, and (b) avoids GDPR (hopefully).
> Contacts people

- Contacts/People/authors.html
- Contacts/People/modules.html
- Packages/Authors/authors.html
- Packages/Authors/index.html
- Packages/Authors/index.mixer
- Packages/Authors/pkgauthorhints.html
- Packages/Authors/variablenames.html
- Packages/Contrib/cliffordmatrices.html
- Packages/Contrib/commsemi.html
- Packages/Contrib/contrib.html
- Packages/Contrib/emacs.html
- Packages/Contrib/index.html
- Packages/Contrib/index.mixer
- Packages/Contrib/timers.html
- Packages/undep.html
Also use accents for Isabel Araújo
> Jekyll: Packages/Authors, Packages/Contrib, Packages/undep

- Packages/undep.html
> fix link to one package

- Overview/interface.html
- Packages/packages.html
- Packages/undep.html
just a few typos found using codespell
> some typos

- etc/LinksOfAllHelpSections.g
- etc/rebuild_Packages_dir.sh
- etc/release_helper.sh
This is a work in progress but is necessary for the others working on the release automation to test my script.
> Add some new scripts to generate stuff, and tweaks

- _layouts/packages.html
- css/gw.css
I've put together a new layout.
No content has been removed.
Some content has been reorganised.
> pkg pages layout changed

- _includes/packagename_to_html.html
- _layouts/packages.html
> Make package dependencies into clickable links

- Contacts/People/Council/council.md
@beick please let me know if there are further changes needed.
> Update council page (only merge on or after October 1st!)

- Doc/manuals.html
- README.md
- _layouts/packages.html
- etc/pkglinks.py
This fixes several problem with links to manuals and links between manuals for the GAP website.
> Fixes manual links

- Contacts/Forum/forum.html
> Update instructions for subscribing to the GAP forum

- Doc/Learning/learning.html
- Doc/doc.html
- Doc/manuals.html
- Download/index.html
- Overview/overview.html
> Link to to chap0_mj.html not chap0.html for the GAP manuals

- Doc/doc.html
This doesn't exist anymore, link to CHANGES.md instead
> Replace link to changes manual

- .htaccess
> Add redirect for old MacTutor URLs

- Doc/Teaching/teaching.html
- Faq/faq.html
... as I believe it no longer exists, right, @olexandr-konovalov?
> Remove link to russian FAQ

- Contacts/People/Council/council.md
- Contacts/People/people.md
- Contacts/submit.md
- Packages/Authors/authors.html
- Packages/packages.html
By consensus of the members of the GAP council
> GAP package refereeing is being abolished

- Packages/packages.html
- _layouts/core.html
From GAPDays Spring 2024. Includes new list, that is searchable and unified.
> Add new package list

- packages/authors/submit.md
This is just a link I went to click on, and found it needed pointing to right page (the page mentioned doesn't exist).
> Fix broken link

- index.md
> fix: broken package submition link - #374

- assets/js/loadPackageTable.js
> Correctly handle packages without IssueTrackerURL

- Gemfile
> Add missing dependencies to Gemfile

- logo/index.md
> Fix typos in GAP logo page
